"""empty message

Revision ID: 0844831b2263
Revises: 12af97a9c13d
Create Date: 2022-11-10 11:27:23.573531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0844831b2263'
down_revision = '12af97a9c13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'Login', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Login', type_='unique')
    op.drop_column('Login', 'public_id')
    # ### end Alembic commands ###
