"""empty message

Revision ID: 12af97a9c13d
Revises: 
Create Date: 2022-11-09 16:30:54.751140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12af97a9c13d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Login')
    # ### end Alembic commands ###
