"""empty message

Revision ID: 41435457084d
Revises: 0844831b2263
Create Date: 2022-11-11 11:28:17.504083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41435457084d'
down_revision = '0844831b2263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Persons')
    op.drop_table('Test')
    op.add_column('Login', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_index('email', table_name='Login')
    op.drop_index('public_id', table_name='Login')
    op.drop_column('Login', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('public_id', 'Login', ['public_id'], unique=False)
    op.create_index('email', 'Login', ['email'], unique=False)
    op.drop_column('Login', 'admin')
    op.create_table('Test',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tm_fixed_cost', mysql.FLOAT(), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resources', mysql.JSON(), nullable=True),
    sa.Column('logo_url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('overall_completion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('deleted_by', mysql.VARCHAR(length=40), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Persons',
    sa.Column('PersonID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
