"""empty message

Revision ID: 49e7c86f8362
Revises: c83253d6cb28
Create Date: 2022-11-11 12:28:39.868695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49e7c86f8362'
down_revision = 'c83253d6cb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_column('Login', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('name', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('Login', 'username')
    # ### end Alembic commands ###
