"""empty message

Revision ID: c83253d6cb28
Revises: 41435457084d
Create Date: 2022-11-11 12:28:12.792125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c83253d6cb28'
down_revision = '41435457084d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('email', sa.String(length=50), nullable=True))
    op.drop_column('Login', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('Login', 'email')
    # ### end Alembic commands ###
